name: tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linux_tests:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: true
      matrix:
        php: [8.0, 8.1]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, fileinfo
          tools: composer:v2
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --prefer-dist

      - name: Execute tests
        run: vendor/bin/phpunit --verbose
